licenses(['notice'])

java_library(
    name = 'poi',
    visibility = [
        '//visibility:public',
    ],
    srcs = glob([
        'src/main/**/*.java',
    ]),
    resources = ['src/main/resources/application.conf'],
    deps = [
        '@aliyun_sdk_oss//jar',
        '@bcpkix_jdk15on//jar',
        '@bcprov_jdk15on//jar',
        '@commons_codec//jar',
        '@commons_collections4//jar',
        '@commons_logging//jar',
        '@config//jar',
        '@curvesapi//jar',
        '@druid//jar',
        '@error_prone_annotations//jar',
        '@fastjson//jar',
        '@grpc_context//jar',
        '@grpc_core//jar',
        '@grpc_netty//jar',
        '@grpc_protobuf//jar',
        '@grpc_protobuf_lite//jar',
        '@grpc_stub//jar',
        '@gson//jar',
        '@guava//jar',
        '@hamcrest_core//jar',
        '@httpclient//jar',
        '@httpcore//jar',
        '@instrumentation_api//jar',
        '@jdom//jar',
        '@jsr305//jar',
        '@junit//jar',
        '@log4j//jar',
        '@mysql_connector_java//jar',
        '@netty_buffer//jar',
        '@netty_codec//jar',
        '@netty_codec_http//jar',
        '@netty_codec_http2//jar',
        '@netty_codec_socks//jar',
        '@netty_common//jar',
        '@netty_handler//jar',
        '@netty_handler_proxy//jar',
        '@netty_resolver//jar',
        '@netty_transport//jar',
        '@ooxml_schemas//jar',
        '@ooxml_security//jar',
        '@opencensus_api//jar',
        '@opencensus_contrib_grpc_metrics//jar',
        '@poi//jar',
        '@poi_ooxml//jar',
        '@poi_ooxml_schemas//jar',
        '@proto_google_common_protos//jar',
        '@protobuf_java//jar',
        '@protobuf_java_util//jar',
        '@slf4j_api//jar',
        '@stax2_api//jar',
        '@stax_api//jar',
        '@woodstox_core_asl//jar',
        '@xmlbeans//jar',
        '@xmlsec//jar',
    ],
)

java_test(
    name = 'poi_test',
    srcs = glob([
        'src/test/**/*.java',
    ]),
    deps = [
        ':poi',
    ],
)
